services:
  ms-transaction:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: transaction
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '${PORT}:3001'
    env_file:
      - .env
    networks:
      - shared-network-ms

networks:
  shared-network-ms:
    external: true
